<?php
/**
 * R2 / Public S3 Sync for Virtual Commissary (Bypasses bot protection)
 * Location: wp-content/plugins/srl-league-system/includes/commissary/r2-sync.php
 *
 * @package SRL_League_System
 */

if ( ! defined( 'WPINC' ) ) die;

/**
 * Record a diagnostic probe log entry.
 *
 * @param int    $protest_id Target protest ID or 0 for general.
 * @param string $target_url The URL or object key probed.
 * @param int|string $http_code HTTP response code or error string.
 * @param string $status SUCCESS, NOT_FOUND, ERROR, SKIPPED, etc.
 * @param string $message Detailed description.
 */
function srl_log_commissary_probe( $protest_id, $target_url, $http_code, $status, $message ) {
    $logs = get_option( 'srl_commissary_probe_logs', [] );
    if ( ! is_array( $logs ) ) {
        $logs = [];
    }

    $entry = [
        'time'       => current_time( 'Y-m-d H:i:s' ),
        'protest_id' => intval( $protest_id ),
        'target_url' => esc_url_raw( $target_url ),
        'http_code'  => is_numeric( $http_code ) ? intval( $http_code ) : sanitize_text_field( $http_code ),
        'status'     => sanitize_key( $status ),
        'message'    => sanitize_text_field( $message ),
    ];

    array_unshift( $logs, $entry );
    if ( count( $logs ) > 50 ) {
        $logs = array_slice( $logs, 0, 50 );
    }
    update_option( 'srl_commissary_probe_logs', $logs );

    // Also update single post meta for easy viewing in the protest editor
    if ( $protest_id > 0 ) {
        update_post_meta( $protest_id, '_srl_last_probe_log', $entry );
    }

    // Server error log for debugging
    error_log( sprintf( '[SRL Commissary Sync] #%d | %s | HTTP %s | %s: %s', $protest_id, $target_url, $http_code, $status, $message ) );
}

// Lightweight transient-based cron replacement to bypass InfinityFree WP-Cron blocks
add_action( 'init', 'srl_lightweight_r2_sync_cron' );
function srl_lightweight_r2_sync_cron() {
    // Only run every 5 minutes (300 seconds) on public page loads
    if ( false === get_transient( 'srl_r2_sync_lock' ) ) {
        set_transient( 'srl_r2_sync_lock', true, 300 );
        srl_process_r2_verdicts_handler();
    }
}

/**
 * Checks for verdicts generated by n8n in the Cloudflare R2 bucket or Public Custom Domain.
 *
 * @param int $specific_protest_id Optional protest ID to check specifically.
 * @return array Results summary.
 */
function srl_process_r2_verdicts_handler( $specific_protest_id = 0 ) {
    $public_verdicts_url = trim( get_option( 'srl_virtual_commissary_verdicts_url', 'https://srl-veredicts.imevca.qzz.io' ) );
    $r2_enabled = class_exists( 'SRL_R2_Uploader' ) && SRL_R2_Uploader::is_enabled();

    // Guard: We need at least the public URL or the R2 API configured
    if ( empty( $public_verdicts_url ) && ! $r2_enabled ) {
        srl_log_commissary_probe( 0, 'none', 'N/A', 'CONFIG_ERROR', 'Sondeo abortado: Ni la URL pública ni las credenciales R2 están configuradas.' );
        return [ 'success' => false, 'message' => 'Ni la URL pública ni las credenciales R2 están configuradas.' ];
    }

    // Build query
    $query_args = [
        'post_type'      => 'srl_protest',
        'post_status'    => 'publish',
        'posts_per_page' => 20,
    ];

    if ( $specific_protest_id > 0 ) {
        $query_args['p'] = $specific_protest_id;
    } else {
        $query_args['meta_query'] = [
            [
                'key'   => '_srl_ai_status',
                'value' => 'processing',
            ],
        ];
    }

    $query = new WP_Query( $query_args );

    if ( ! $query->have_posts() ) {
        if ( $specific_protest_id > 0 ) {
            srl_log_commissary_probe( $specific_protest_id, 'query', '404', 'NOT_FOUND', 'No se encontró el reclamo especificado.' );
        }
        return [ 'success' => true, 'count' => 0, 'message' => 'No hay reclamos en estado de procesamiento.' ];
    }

    $processed_count = 0;

    foreach ( $query->posts as $post ) {
        $protest_id = $post->ID;
        $object_key_root = 'protest_' . $protest_id . '.json';
        $object_key_folder = 'srl-verdicts/' . $object_key_root;

        $response = [ 'success' => false ];
        $object_key = $object_key_root;
        $probe_url = '';
        $http_code = 0;

        // 1. Try public custom domain first
        if ( ! empty( $public_verdicts_url ) ) {
            $probe_url = trailingslashit( $public_verdicts_url ) . $object_key_root;
            $http_response = wp_remote_get( $probe_url, [
                'timeout'    => 15,
                'user-agent' => 'SRL-League-System-Sync/1.13.8',
            ] );

            if ( is_wp_error( $http_response ) ) {
                $http_code = 'ERR';
                srl_log_commissary_probe( $protest_id, $probe_url, $http_code, 'HTTP_ERROR', $http_response->get_error_message() );
            } else {
                $http_code = wp_remote_retrieve_response_code( $http_response );
                if ( $http_code === 200 ) {
                    $body = wp_remote_retrieve_body( $http_response );
                    if ( ! empty( $body ) ) {
                        $response = [
                            'success' => true,
                            'body'    => $body,
                        ];
                    }
                } else {
                    srl_log_commissary_probe( $protest_id, $probe_url, $http_code, 'PENDING', 'Archivo no disponible aún en URL pública.' );
                }
            }
        }

        // 2. Fallback to direct R2 SigV4 API if public URL failed or is empty
        if ( ! $response['success'] && $r2_enabled ) {
            // Check folder path
            $r2_res = SRL_R2_Uploader::get_object( $object_key_folder );
            if ( $r2_res['success'] ) {
                $response = $r2_res;
                $object_key = $object_key_folder;
                $probe_url = 'R2://' . $object_key_folder;
                $http_code = 200;
            } else {
                // Check root path
                $r2_res = SRL_R2_Uploader::get_object( $object_key_root );
                if ( $r2_res['success'] ) {
                    $response = $r2_res;
                    $object_key = $object_key_root;
                    $probe_url = 'R2://' . $object_key_root;
                    $http_code = 200;
                } else {
                    $probe_url = 'R2://' . $object_key_root;
                    $http_code = $r2_res['code'] ?? '404';
                    srl_log_commissary_probe( $protest_id, $probe_url, $http_code, 'PENDING', 'No encontrado en R2 API.' );
                }
            }
        }

        if ( ! $response['success'] ) {
            continue;
        }

        // 3. File exists! Parse payload
        $json_data = $response['body'];
        $raw_verdict = json_decode( $json_data, true );
        $verdict = null;

        // Unpack if wrapped in n8n [{"text": "```json...```"}] array format
        if ( is_array( $raw_verdict ) && isset( $raw_verdict[0]['text'] ) ) {
            $text = $raw_verdict[0]['text'];
            if ( preg_match( '/```(?:json)?\s*(\{.*?\})\s*```/is', $text, $matches ) ) {
                $verdict = json_decode( $matches[1], true );
            } else {
                $verdict = json_decode( $text, true );
            }
        } elseif ( is_array( $raw_verdict ) && isset( $raw_verdict['text'] ) ) {
            $text = $raw_verdict['text'];
            if ( preg_match( '/```(?:json)?\s*(\{.*?\})\s*```/is', $text, $matches ) ) {
                $verdict = json_decode( $matches[1], true );
            } else {
                $verdict = json_decode( $text, true );
            }
        } else {
            $verdict = $raw_verdict;
        }

        // Validate that we got a valid verdict structure
        $is_valid = is_array( $verdict ) && (
            isset( $verdict['fault_protesting'] ) ||
            isset( $verdict['chief_steward'] ) ||
            isset( $verdict['penalty'] ) ||
            isset( $verdict['rationale'] )
        );

        if ( ! $is_valid ) {
            update_post_meta( $protest_id, '_srl_ai_status', 'failed' );
            update_post_meta( $protest_id, '_srl_ai_error', 'Formato JSON inválido de la IA. Raw: ' . substr( $json_data, 0, 150 ) );
            srl_log_commissary_probe( $protest_id, $probe_url, 200, 'JSON_INVALID', 'Archivo recuperado pero no tiene la estructura de veredicto esperada.' );
            continue;
        }

        // 4. Save and mark completed!
        update_post_meta( $protest_id, '_srl_ai_status', 'completed' );
        update_post_meta( $protest_id, '_srl_ai_verdict', wp_json_encode( $verdict ) );
        update_post_meta( $protest_id, '_srl_ai_error', '' );
        update_post_meta( $protest_id, '_srl_ai_processed_at', current_time( 'mysql' ) );

        srl_log_commissary_probe( $protest_id, $probe_url, 200, 'SUCCESS', '¡Veredicto recuperado e importado con éxito!' );
        $processed_count++;

        // Clean up from R2 bucket if R2 credentials exist
        if ( $r2_enabled ) {
            SRL_R2_Uploader::delete_object( $object_key );
        }
    }

    return [
        'success'   => true,
        'count'     => $processed_count,
        'message'   => sprintf( 'Sondeo completado. Se procesaron %d veredictos.', $processed_count ),
    ];
}

/**
 * AJAX Handler: Manual check for a single protest from the editor screen.
 */
add_action( 'wp_ajax_srl_manual_check_verdict', 'srl_ajax_manual_check_verdict' );
function srl_ajax_manual_check_verdict() {
    check_ajax_referer( 'srl-ajax-nonce', 'nonce' );

    if ( ! current_user_can( 'manage_options' ) ) {
        wp_send_json_error( [ 'message' => 'Permisos insuficientes.' ] );
    }

    $protest_id = isset( $_POST['protest_id'] ) ? intval( $_POST['protest_id'] ) : 0;
    if ( ! $protest_id ) {
        wp_send_json_error( [ 'message' => 'ID de reclamo inválido.' ] );
    }

    // Force probe bypass
    delete_transient( 'srl_r2_sync_lock' );
    $res = srl_process_r2_verdicts_handler( $protest_id );

    $status = get_post_meta( $protest_id, '_srl_ai_status', true );
    $last_probe = get_post_meta( $protest_id, '_srl_last_probe_log', true );

    wp_send_json_success( [
        'message'    => $res['message'] ?? 'Sondeo finalizado.',
        'status'     => $status,
        'last_probe' => $last_probe,
    ] );
}

/**
 * AJAX Handler: Trigger global sync from the Settings page.
 */
add_action( 'wp_ajax_srl_trigger_global_sync', 'srl_ajax_trigger_global_sync' );
function srl_ajax_trigger_global_sync() {
    check_ajax_referer( 'srl-ajax-nonce', 'nonce' );

    if ( ! current_user_can( 'manage_options' ) ) {
        wp_send_json_error( [ 'message' => 'Permisos insuficientes.' ] );
    }

    delete_transient( 'srl_r2_sync_lock' );
    $res = srl_process_r2_verdicts_handler();
    $logs = get_option( 'srl_commissary_probe_logs', [] );

    wp_send_json_success( [
        'message' => $res['message'] ?? 'Sondeo completado.',
        'logs'    => $logs,
    ] );
}

/**
 * AJAX Handler: Clear probe logs.
 */
add_action( 'wp_ajax_srl_clear_probe_logs', 'srl_ajax_clear_probe_logs' );
function srl_ajax_clear_probe_logs() {
    check_ajax_referer( 'srl-ajax-nonce', 'nonce' );

    if ( ! current_user_can( 'manage_options' ) ) {
        wp_send_json_error( [ 'message' => 'Permisos insuficientes.' ] );
    }

    delete_option( 'srl_commissary_probe_logs' );
    wp_send_json_success( [ 'message' => 'Logs eliminados correctamente.' ] );
}

