<?php
/**
 * R2 Sync for Virtual Commissary (Bypasses bot protection)
 * Location: wp-content/plugins/srl-league-system/includes/commissary/r2-sync.php
 *
 * @package SRL_League_System
 */

if ( ! defined( 'WPINC' ) ) die;

// Register the custom cron schedule (every 5 minutes)
add_filter( 'cron_schedules', 'srl_r2_add_cron_interval' );
function srl_r2_add_cron_interval( $schedules ) {
    $schedules['every_five_minutes'] = array(
        'interval' => 300,
        'display'  => esc_html__( 'Every 5 Minutes' ),
    );
    return $schedules;
}

// Schedule the cron event on init if not scheduled
add_action( 'init', 'srl_schedule_r2_sync_cron' );
function srl_schedule_r2_sync_cron() {
    if ( ! wp_next_scheduled( 'srl_process_r2_verdicts_cron' ) ) {
        wp_schedule_event( time(), 'every_five_minutes', 'srl_process_r2_verdicts_cron' );
    }
}

// The cron job hook
add_action( 'srl_process_r2_verdicts_cron', 'srl_process_r2_verdicts_handler' );

/**
 * Checks for verdicts generated by n8n in the Cloudflare R2 bucket.
 */
function srl_process_r2_verdicts_handler() {
    if ( ! class_exists( 'SRL_R2_Uploader' ) || ! SRL_R2_Uploader::is_enabled() ) {
        return;
    }

    // Find all protests currently being processed by AI
    $query = new WP_Query([
        'post_type'      => 'srl_protest',
        'post_status'    => 'publish',
        'posts_per_page' => 20,
        'meta_query'     => [
            [
                'key'   => '_srl_ai_status',
                'value' => 'processing',
            ],
        ],
    ]);

    if ( ! $query->have_posts() ) {
        return;
    }

    foreach ( $query->posts as $post ) {
        $protest_id = $post->ID;
        
        $object_key_folder = 'srl-verdicts/protest_' . $protest_id . '.json';
        $object_key_root = 'protest_' . $protest_id . '.json';

        // Attempt to fetch the verdict file from folder
        $response = SRL_R2_Uploader::get_object( $object_key_folder );
        $object_key = $object_key_folder;

        if ( ! $response['success'] ) {
            // Try root path
            $response = SRL_R2_Uploader::get_object( $object_key_root );
            $object_key = $object_key_root;
        }

        if ( ! $response['success'] ) {
            // File might not be ready yet (404) or another error occurred. Skip for now.
            continue;
        }

        $json_data = $response['body'];
        $verdict = json_decode( $json_data, true );

        if ( ! is_array( $verdict ) ) {
            // Invalid JSON, mark as failed
            update_post_meta( $protest_id, '_srl_ai_status', 'failed' );
            update_post_meta( $protest_id, '_srl_ai_error', 'Respuesta JSON inválida de la IA.' );
            // Clean up the corrupt file from R2
            SRL_R2_Uploader::delete_object( $object_key );
            continue;
        }

        // Successfully received the verdict! Apply it.
        update_post_meta( $protest_id, '_srl_ai_status', 'completed' );
        update_post_meta( $protest_id, '_srl_ai_verdict', wp_json_encode( $verdict ) );
        update_post_meta( $protest_id, '_srl_ai_error', '' );
        update_post_meta( $protest_id, '_srl_ai_processed_at', current_time( 'mysql' ) );

        // Clean up the file from R2 to save space and prevent reprocessing
        SRL_R2_Uploader::delete_object( $object_key );
    }
}
